## Looking For Common Threads Across Successful Seasons
This notebook will aim to answer my first research question and identify common elements across successful seasons throughout the history of the Houston Texans

In [1]:
# Import libraries
import pandas as pd
from sqlalchemy import create_engine
import os
from dotenv import load_dotenv

In [2]:
# Connect to PostgreSQL database
load_dotenv()

DB_NAME = os.getenv('DB_NAME')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')
DB_PORT = os.getenv('DB_PORT')
DB_HOST = os.getenv('DB_HOST')

engine = create_engine(f'postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}')

In [3]:
# Look at summary of all Texans seasons
query = """SELECT * FROM texans_season_summary"""
season_summary = pd.read_sql(query, engine)
season_summary

,season,games_played,wins,win_pct,made_playoffs,turnover_margin,redzone_td_pct_differential,epa_differential
0,2002,16,4,0.250,0,-7.0,-0.042,-0.153
1,2003,16,5,0.313,0,-5.0,0.174,-0.138
2,2004,16,7,0.438,0,5.0,0.033,-0.019
3,2005,16,2,0.125,0,-8.0,-0.154,-0.193
4,2006,16,6,0.375,0,-3.0,0.091,-0.087
5,2007,16,8,0.500,0,-13.0,-0.014,-0.052
6,2008,16,8,0.500,0,-10.0,-0.108,-0.030
7,2009,16,9,0.563,0,-1.0,-0.010,0.092
8,2010,16,6,0.375,0,0.0,-0.027,-0.043
9,2011,16,10,0.625,1,6.0,-0.009,0.168
10,2012,16,12,0.750,1,11.0,0.085,0.136
11,2013,16,2,0.125,0,-20.0,-0.069,-0.127
12,2014,16,9,0.563,0,12.0,0.022,0.100
13,2015,16,9,0.563,1,1.0,0.054,0.032
14,2016,16,9,0.563,1,-4.0,-0.071,-0.011
15,2017,16,4,0.250,0,-12.0,-0.089,-0.083
16,2018,16,11,0.688,1,13.0,-0.161,0.056
17,2019,16,10,0.625,1,0.0,-0.095,-0.029
18,2020,16,4,0.250,0,-9.0,-0.101,-0.059
19,2021,17,4,0.235,0,3.0,-0.153,-0.202
20,2022,17,3,0.176,0,-1.0,-0.078,-0.182
21,2023,17,10,0.588,1,12.0,-0.049,0.019
22,2024,17,10,0.588,1,10.0,0.002,0.037
23,2025,17,12,0.706,1,14.0,-0.095,0.125

In [4]:
# Correlations against win_pct
metrics = ['turnover_margin', 'redzone_td_pct_differential', 'epa_differential']
season_summary[metrics + ['win_pct']].corr()['win_pct'].drop('win_pct')

turnover_margin                0.702389
redzone_td_pct_differential    0.197846
epa_differential               0.889947
Name: win_pct, dtype: float64

It makes sense that EPA differential is the strongest single predictor of win_pct as EPA differential is basically saying "how much better were you than your opponent".

Turnover margin also shows a strong correlation with win_pct, which indicates that a strong defense and safe offense could lead to success.

In [5]:
# Comparison against made_playoffs
season_summary.groupby('made_playoffs')[metrics].mean()

               turnover_margin  redzone_td_pct_differential  epa_differential
made_playoffs
0                         -4.6                    -0.035000         -0.078400
1                          7.0                    -0.037667          0.059222

Unsurprisingly, turnover margin has been high on years that the Texans have made the playoffs and negative in years where they did not. Also, as a longtime fan, it isn't surprising that the redzone td pct differential isn't too different between playoff and non-playoff seasons.